### ISSUE TITLE
installation 

### ISSUE THREAD

**Issue by maku1958** [vdr-projects/vdr-plugin-vdrmanager#1]
Hello,
I tried to install via the vdr-wiki but it did not work.
1. after git clone https://github.com/vdr-projects/vdr-plugin-vdrmanager.git --- i have 6 directories
2. archlinux  gentoo  release  resources  vdrmanager  vdr-vdrmanager
3. I'm running ubuntu server 22.04 LTS and vdr 2.6.0 headless on the server
4. the vdr-wiki wants to unpack an  tar.gz to find in directory "release"
5. I used the 0.11.tar.gz -- make plugins ends with "nothing to do"

Where do I have to start?
Thanks in advance for your asisstence.
Manfred

**Comment by M-Reimer** [comment]
You should ignore VDR-Wiki. There is no administrator who still manages the Wiki and several attempts of people, who wanted to take over administration, failed. So I guess VDR-Wiki is dead.

Ignore the "release" directory (probably it should be deleted altogether as pushing tarballs to GIT is not a good idea).

You find the plugin sources below "vdr-vdrmanager" which is a "regular VDR plugin" that can be built the same way as you build other plugins.

And for getting release packages, best go to: https://github.com/vdr-projects/vdr-plugin-vdrmanager/tags

Please tell me if this helped.

**Comment by maku1958** [comment]
Thank you for your reply.
I have found an ubuntu-site to VDR there is the installation explained. 
I managed to run the the vdrmanager on my server.
